name: Build & Upload

on:
  push:
    branches: [ master ]
    paths:
      - "pom.xml"
      - "src/main/java/**/*.java"
      - "src/main/resources/**/*.*"
  pull_request:
    branches: [ master ]
    paths:
      - "pom.xml"
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Unshallow
        run: git fetch --unshallow --quiet
      - name: Build with Maven
        run: mvn -B package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: "BetterSkyWars"
          path: "./target/BetterSkyWars*.jar"
